// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fruxnbqqokwdzldjduql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydXhuYnFxb2t3ZHpsZGpkdXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjUyNDMsImV4cCI6MjA2NDE0MTI0M30.0aFRGTaMOmUyot537W7aVpuG9BQ_aVtAm1HcwG8jmKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);